# Build stage
FROM golang:1.20-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /open-ndi-sender ./cmd/sender

# Final image
FROM alpine:3.16
COPY --from=builder /open-ndi-sender /usr/local/bin/
ENTRYPOINT ["/usr/local/bin/open-ndi-sender"]